before_install:
  - chmod +x gradlew

language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "microscape-io" # the key of the org you chose at step #3
    token:
      secure: "S3Ut3eIRM3Qi4YxcIIl8pIMsAaeLQjbvAIIa/o/NPFYaYlLXo+jPo6mJRpcpa7sId9EgbE+rUp73UNfQ3cpHKqXt7T1QhbEbcxp6DsW1ah2a/EHSGN0UN/eM7Y5i2Ow7ibWqCYj4upyPZqrW8qg6x0SzZLNdNW1eX4LAFEXfXTFmQQlGJ1SeI0IBxKAsWqnZqNaLAQfBaiGv/RR5e2xgtptFH4AejPlTjrbyoKyxC+s7pOq9ZOggaxILxq4K5KaaWIoraxzHk2GjN2pcq4c1KJD30To0UieqRoTNA8vBe6DJEB4wDM+f1Tsvcl607rT/p/KRGtZpHOwnZntKGfiY8D1fJfcbneZ7TB6MSE6/RWaslZ82xTZdsGs/dX8h2YpVExoudFudDkKookJe75UWO4SOkd0g7tfWVpXhPjNrvG6jZngzWZU5u2fa5rXbsVNdbzfWh/038PFrRI5dxsQHrAVwTnUHloa375X8aRL/DMsYHFfW5Ned/5XY9CiYba5l6Nt8DdOYkHfxyOajAdCljCPH2S+awFXjVxQYvGarXkyfkbU0Cr6fIDpyTpFUTchlCVx79Uq8AugEMbHxg0fpt8LANLdaHDdTi6nYbrQOspHoiMddXVQwoLxULBkDwu7/OpZIBTt81f6w8ecFvDagQpe29PJKMmO6+dLqHq7WXJg="
    branches:
      - master
      - development

script:
  - ./gradlew check sonarqube
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: WfPZ3fg4g4M+A53gFzdBxdMXkOxhE/1vfeHXw8rAKkJyZJCQeLyQToO0Ekr5t/db3+ceClvoyngXNxQTzrbG5E9SJxUU/zMAoNHP7iJLEb64O6vZv9BEUMj2kDYGG5a7Ke3CG3gjjDb2qp32+wK7ibPRXRTQOsTIjJJtwyc4om663TPpvjQarLKXp54BkjBRdPhF/AADvKcFTWWMh9pzhFQOLJRlUb7ej/dm7l6hpPmPFAf/Rvq4mbTtp6DfxUf+YKpEtRD8zNE1k/lJ1KQeAOI82gKEy5zB+N0m+32X9i2o/osC2gR/tJdMc/fH6I2kyIMaCmvXWdfRlN/xSc/kyCEbZlyVoiMJUfshpv1R+hcklznHY0zoKKEii6BvQTpZRysPG8okZOmgXAQwjeIfqjwr3p3g8bWd0qJhZaxGD14j9eKYZAcah7edbYL0xARG2Kpza0J/BovbMP+rrVZpH/y9TyO3nrFLxkG5+nVmJCFwSPQiqw54tU9xVFtAmTOX0CxnkMtz5z577GNVvCQnUsnRkC2rXocqSjH216Zzz56Q1YyOrbk1x9VvysSD3o+G9R2Gm9E03DgIkCxD+SNzTwKjLIFXv4dM27iI/d7F1NF5DiSVQNIfDIqP0cLhbbn6pqayAYFs5t5tFlc11pAVO9DvAn/8UJkk7DHGGa+Ov6o=
